language: node_js
node_js:
  - "lts/*"
  - "node"

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
script:
  - yarn test

after_script: greenkeeper-lockfile-upload
